name: Core
version: '${project.version}'
main: de.jan.rpg.core.Core
api-version: '1.21'
author: Jan2808
description: CoreSystem for the RPG-System

commands:
  core:
    description: manage all core commands
    permission: highs that even possible and a bit more....